#!/usr/bin/env python3
"""init.sh template generator and safety helpers.

Author: Damon Li
"""

from __future__ import annotations

from pathlib import Path

INIT_SCRIPT_TEMPLATE = """#!/usr/bin/env bash
# Project bootstrap script generated by agenticx project_state.
# Edit freely. Must be idempotent: rerunning should not break the workspace.

set -euo pipefail

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/../.." && pwd)"
cd "$ROOT"

echo "[init.sh] workspace: $ROOT"

# 1. Install dependencies (replace with your project's package manager).
# Example for Python projects:
#   python -m pip install -e .
# Example for Node projects:
#   npm install --no-audit --no-fund

# 2. Apply database migrations / generate seed data here (if any).

# 3. Compile assets / generate code (if any).

echo "[init.sh] done"
"""

VERIFY_YAML_TEMPLATE = """schema_version: 1
# Project verification gate. Each step must exit 0. The runner stops on the
# first failure and writes the tail of the failing log under archive/.
steps:
  - name: bootstrap
    type: shell
    cmd: bash .agx/project/init.sh
    timeout_sec: 600

  # Replace the following with your real test suite. Examples:
  # - name: pytest
  #   type: pytest
  #   args: ["-q", "tests/test_smoke_*.py"]
  #
  # - name: lint
  #   type: shell
  #   cmd: ruff check .
  #   timeout_sec: 120
"""


def write_default_init_script(path: Path) -> Path:
    """Write the init.sh template if absent and mark it executable."""
    target = Path(path)
    target.parent.mkdir(parents=True, exist_ok=True)
    if not target.exists():
        target.write_text(INIT_SCRIPT_TEMPLATE, encoding="utf-8")
    try:
        mode = target.stat().st_mode | 0o755
        target.chmod(mode)
    except OSError:
        pass
    return target


def write_default_verify_yaml(path: Path) -> Path:
    """Write the verify.yaml template if absent."""
    target = Path(path)
    target.parent.mkdir(parents=True, exist_ok=True)
    if not target.exists():
        target.write_text(VERIFY_YAML_TEMPLATE, encoding="utf-8")
    return target
